[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
token_minter = "7ctquMoeUnksYS6doBpqgnEmya2oc7ZCivKCjMhzenwf"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "/Users/es/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
