[features]
seeds = false
skip-lint = false
[programs.devnet]
token_minter = "GMe6HHNcxLr7hnDg4ToN4MdhJj7KKSxATqDANKZJXmwo"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/Users/es/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
